---
# Playbook for the cloud deployment. Ordering is important as a deployment is sequential. 
# Variables for the cloud configuration are defined globally in ./vars/main.yml

- hosts: all
  tags: wait
  gather_facts: no
  tasks:
  - name: Wait for SSH
    local_action: wait_for port=22 timeout=900 host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %}
  vars_files:
    - "vars/main.yml"
    - [ "vars/euca_{{ euca_version }}.yml", ]
  roles:
    - common

- hosts: nc
  vars_files:
    - "vars/main.yml"
    - [ "vars/euca_{{ euca_version }}.yml", ]
  roles:
    - nc

- hosts: clc
  vars_files:
    - vars/main.yml
    - [ "vars/euca_{{ euca_version }}.yml", ]
  roles:
    - clc

- hosts: walrus
  vars_files:
    - vars/main.yml
    - [ "vars/euca_{{ euca_version }}.yml", ]
  roles:
    - walrus

- hosts: cc
  vars_files:
    - vars/main.yml
    - [ "vars/euca_{{ euca_version }}.yml", ]
  roles:
    - cc

- hosts: sc
  vars_files:
    - vars/main.yml
    - [ "vars/euca_{{ euca_version }}.yml", ]
  roles:
    - sc

